<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tequila Wings</title>
    <link rel="shortcut icon" href="Hotelloicon3.png" type="image/x-icon">
    <link rel="stylesheet" href="{{ asset('assets/estilos.css') }}">
</head>
<body>
    <a name="ainicio"></a>
    <header>
        <nav class="barra">
            <a href="#ainicio">INICIO</a>
            <a href="#database">BASE DE DATOS</a>
            <a href="#acromos">UTILIDADES</a>
            <a href="#acollage">HERRAMIENTAS</a>
            <a href="#ametodologia">CONTACTO</a>
            <a href="#acontacto">>>></a>
        </nav>
        <section class="textos-header">
            <img src="assets/TequilaWings.svg" alt="">

        </section>
        <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->

        <div class="wave" style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C149.99,150.00 349.20,-49.98 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: rgb(0,0,0);"></path></svg></div>
    </header>
    <main>
        <section class="sobre-nosotros">
            <h2 class="titulo">
                TEQUILA WINGS
            </h2>
            <div class="contenedor-sobre-nosotros">
                <!--<img src="assets/NotFound3.svg" alt="" class="imagen-about-us">-->
                <div class="contenido-textos">
                    <h3>| SNACKS | BEER | MUSIC |</h3>
                </div>
            </div>
            
        </section>
        
        <div style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C154.34,111.02 271.49,-49.98 500.00,49.98 L500.00,0.00 L0.00,0.00 Z" style="stroke: none; fill: rgb(0,0,0);"></path></svg></div>

        <a name="database"></a>
        <section class="tequilawingsbuttons">
            <h1>BASE DE DATOS</h1>
            <form action="/alimento">
                <button type="submit">ALIMENTOS</button>
            </form>
            <form action="/bebida">
                <button type="submit">BEBIDAS</button>
            </form>
                        
        </section>


        <a name="acromos"></a>
        <section class="cromos">
            <div class="contenedor">
                <h2 class="titulocromos">UTILIDADES</h2>
                <div class="galeria-cromos">
                    <div class="imagen-cromo">
                        <img src="assets/NotFoundB.svg" alt="">
                        <div class="hover-galeria">
                            <img src="" alt="">
                            <p>...</p>
                        </div>
                    </div>
                    <div class="imagen-cromo">
                        <img src="assets/NotFoundB.svg" alt="">
                        <div class="hover-galeria">
                            <img src="" alt="">
                            <p>...</p>
                        </div>
                    </div>
                    <div class="imagen-cromo">
                        <img src="assets/NotFoundB.svg" alt="">
                        <div class="hover-galeria">
                            <img src="" alt="">
                            <p>...</p>
                        </div>
                    </div>
                    <div class="imagen-cromo">
                        <img src="assets/NotFoundB.svg" alt="">
                        <div class="hover-galeria">
                            <img src="" alt="">
                            <p>...</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <a name="acollage"></a>
        <section class="collage">
           <h2 class="titulocollage">HERRAMIENTAS</h2>
           <div class="foto-collage">
               <div class="collage-texto">
               </div>
           </div> 
        </section>
        <a name="ametodologia"></a>
        <section class="diagrama">
           <div class="contenedor">
               <h2 class="titulodiagrama">CONTACTO</h2>
           </div> 
        </section>
    </main>
    <a name="acontacto"></a>
    <footer>
        <div class="contenedor-footer">
            <div class="content-foo">
                <h4>Teléfono</h4>
                <p>+01 9375 8474</p>
            </div>
            <div class="content-foo">
                <h4>E-mail</h4>
                <p>tequilawingsrh@gmail.com</p>
            </div>
            <div class="content-foo">
                <h4>Ubicación</h4>
                <p>Sixto Gorjón #119, Tequila, Jal. MX.</p>
            </div>
        </div>
        <h2 class="titulo-final">&copy; Tequila Wings</h2>
    </footer>
    
</body>
</html>